model_id: dsaidgovsg/lionguard-public_harm-v1.0
model_type: ridge
config_file: lionguard_public_harm.onnx
tokenizer: BAAI/bge-large-en-v1.5
embedding_model: BAAI/bge-large-en-v1.5
max_length: 512
batch_size: 32